### ISSUE TITLE
Failsafe from rollbar-gem: Could not send payload due to it being too large after truncating attempts

### ISSUE THREAD

**Issue by lukes** [rollbar/rollbar-gem#94]
Hi, 

We're seeing these errors appear now after upgrading from 11.7 to 12.10. We see around 6-7 occurrence per day in production. 

I only raise this in case it's helpful for you to know that at least someone if encountering this error relatively frequently, and perhaps it's possible to continue to attempt to reduce the payload, or perhaps the method of reduction could be looked at.

Looking at our log, it appears as though the payload size is due to the stacktrace. It may be beneficial to attempt to prune the stacktrace.

**Comment by jasper-fu** [comment]
![image](https://cloud.githubusercontent.com/assets/233379/8642176/d2e8481c-2952-11e5-9ccb-8daa0437666e.png)
Hey, guys, I keep seeing this, what should I do to fix this? thanks

**Comment by jondeandres** [comment]
Hi @jasper-fu, we'll release a new version today or tomorrow. There are some scenarios where active support is breaking the serialization to JSON.

We have a PR for this, https://github.com/rollbar/rollbar-gem/pull/254. But needs to be tested yet.

Sorry for the inconveniences.

**Comment by jondeandres** [comment]
@jasper-fu are you using redis-session-store in your project?

if so, you can ensure that you are configuring the Rails session-store without passing a redis instance, and passing a hash options with the redis initialization options.

**Comment by jasper-fu** [comment]
@jondeandres ok, thanks for helping. :)

**Comment by exterm** [comment]
We have this problem again. Maybe the rollbar guys can check it at https://rollbar.com/Avocadostore/Avocadostore/items/430/ . Is there some way to get more details on the error?

**Comment by jondeandres** [comment]
@exterm are you using Rails? Can you find messages like `[Rollbar]` on logs?

Classname and a backtrace should appear in the logs.

Could you write us `support@rollbar.com`?

**Comment by LucasPadovan** [comment]
We are having the same issue again, this error appears almost every week for any version of the gem, can we do something to deactivate this message? Rollbar is charging us because we have 2k+ of these occurrences...

**Comment by brianr** [comment]
@LucasPadovan Thanks for the report... can you find the `[Rollbar]` messages in your logs that have the details about these errors, and send them to us at `support@rollbar.com`?

It is certainly possible to turn off these messages (you can do so by monkeypatching the gem to have `send_failsafe` do nothing), but we really don't recommend that. When you're getting these, it means there was an error in your application and that there was an error trying to report it to Rollbar. We're very happy to investigate these further; we just need the data from your logs.

**Comment by MaicolBen** [comment]
Same happens to me after upgrade to 2.1.1, now I rollback to 1.4.5 that doesn't happen

**Comment by jondeandres** [comment]
@MaicolBen do you have more details about that payload? it may be long backtraces, or very very long exception class messages.

Could you look into your rails logs for messages with prefix `[Rollbar]`? That will give us more information about the problem.

**Comment by exterm** [comment]
OK, we will downgrade to 1.4.5 as well for now.

@jondeandres still waiting for your answer to my email (@avocadostore.de Address).

**Comment by jondeandres** [comment]
@exterm I answered you :).

**Comment by MaicolBen** [comment]
In my case it is a bug related with delayed jobs and permissions, but I think that a lot of bugs have the same problem with rollbar, I idented it a little:

    [Rollbar] Scheduling payload
    [Rollbar] Sending payload
    [Rollbar] Error processing the payload: NoMethodError, undefined method `key?' for #<JSON::Ext::Generator::State:0x0000000b612dc0>. 
              Payload: {"access_token"=>"31905238562c41ca96c28caff3d9c3b3", 
                        "data"=>{
                            :timestamp=>1439392381, :environment=>"staging", :level=>"error", :language=>"ruby", :framework=>"Rails: 3.2.11", 
                            :server=>{:host=>"ip-172-31-56-128", :root=>"/var/deploy/myapp/web_head/releases/20150811220618", :pid=>21052}, 
                            :notifier=>{:name=>"rollbar-gem", :version=>"2.1.1"}, 
                            :body=>{:trace=>{:frames=>[{:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/bin/rake", :lineno=>23, :method=>"<main>"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/bin/rake", :lineno=>23, :method=>"load"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/bin/rake", :lineno=>33, :method=>"<top (required)>"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>75, :method=>"run"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>176, :method=>"standard_exception_handling"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>78, :method=>"block in run"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>100, :method=>"top_level"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>115, :method=>"run_with_threads"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>106, :method=>"block in top_level"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>106, :method=>"each"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>106, :method=>"block (2 levels) in top_level"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/application.rb", :lineno=>150, :method=>"invoke_task"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb", :lineno=>165, :method=>"invoke"}, 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/rake-10.4.2/lib/rake/task.rb", :lineno=>172, :method=>"invoke_with_call_chain"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/monitor.rb", :lineno=>211, :method=>"mon_synchronize"}, 
                            ... 
                            {:filename=>"/var/deploy/myapp/web_head/shared/bundle/ruby/1.9.1/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"block in initialize"}, 
                            ...
                            {:filename=>"/var/deploy/myapp/web_head/releases/20150811220618/[FILTERED]", :lineno=>160, :method=>"render_by_dimensions"}, 
                            {:filename=>"/var/deploy/myapp/web_head/releases/20150811220618/[FILTERED]", :lineno=>1440, :method=>"pdf_file_path"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>205, :method=>"mkdir_p"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>205, :method=>"each"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>219, :method=>"block in mkdir_p"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>219, :method=>"reverse_each"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>221, :method=>"block (2 levels) in mkdir_p"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>247, :method=>"fu_mkdir"}, 
                            {:filename=>"/usr/local/lib/ruby/1.9.1/fileutils.rb", :lineno=>247, :method=>"mkdir"}], 
                            :exception=>{:class=>"Errno::EACCES", :message=>"Permission denied - [FILTERED]"}, :extra=>{}}}, :uuid=>"4d9d29b7-ce18-4126-8d24-6a936351d551", 
                            :request=>#<Delayed::Backend::ActiveRecord::Job id: 4487, priority: 0, attempts: 5, handler: "--- !ruby/object:Delayed::PerformableMethod\nobject:...", last_error: "Permission denied - [FILTERED]...", run_at: "2015-08-12 15:13:00", 
                                locked_at: "2015-08-12 15:13:01", failed_at: nil, locked_by: "host:ip-172-31-56-128 pid:21052", queue: "server_1_normal", created_at: "2015-08-12 14:55:05", updated_at: "2015-08-12 15:02:30", comments: nil, owner_type: nil, owner_id: nil>}}
    [Rollbar] Reporting internal error encountered while sending data to Rollbar.
    [Rollbar] Sending payload

**Comment by LucasPadovan** [comment]
@brianr I couldn't find any log containing the info from Rollbar errors sorry :( (at least not with my current privileges, im just a programmer at my company).

I'm pretty sure if I change the max payload this will be solved, but i don't know what will be the impact of sending files larger than 200kb to rollbar.

**Comment by KieranP** [comment]
@jondeandres @brianr I am getting the same error as @MaicolBen when using rollbar along with delayed_job.

```
[Rollbar] Error processing the payload: NoMethodError, undefined method `key?' for #<JSON::Ext::Generator::State:0x000000036a9138>.
Payload: {
  "access_token"=>"[hidden]",
  "data"=>{
    :timestamp=>1441663753,
    :environment=>"staging",
    :level=>"error",
    :language=>"ruby",
    :framework=>"Rails: 3.2.22",
    :server=>{
      :host=>"app-server",
      :root=>"/home/user/app/releases/20150907220425",
      :pid=>16785
    },
    :notifier=>{
      :name=>"rollbar-gem",
      :version=>"2.2.1"
    },
    :body=>{
      :trace=>{
        :frames=>[
          {:filename=>"script/delayed_job", :lineno=>5, :method=>"<main>"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>89, :method=>"daemonize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>89, :method=>"times"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>91, :method=>"block in daemonize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>110, :method=>"run_process"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons.rb", :lineno=>192, :method=>"run_proc"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb", :lineno=>88, :method=>"catch_exceptions"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/cmdline.rb", :lineno=>88, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons.rb", :lineno=>193, :method=>"block in run_proc"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/controller.rb", :lineno=>56, :method=>"run"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/application.rb", :lineno=>295, :method=>"start"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/application.rb", :lineno=>269, :method=>"start_proc"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/daemonize.rb", :lineno=>84, :method=>"call_as_daemon"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/daemonize.rb", :lineno=>84, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/application.rb", :lineno=>265, :method=>"block in start_proc"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/daemons-1.2.3/lib/daemons/application.rb", :lineno=>265, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>112, :method=>"block in run_process"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/command.rb", :lineno=>124, :method=>"run"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>146, :method=>"start"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>40, :method=>"run_callbacks"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"execute"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"block in add"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"block in initialize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"block (2 levels) in add"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb", :lineno=>7, :method=>"block (2 levels) in <class:ClearLocks>"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb", :lineno=>7, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>147, :method=>"block in start"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>147, :method=>"loop"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>148, :method=>"block (2 levels) in start"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>40, :method=>"run_callbacks"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"execute"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"block in initialize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>149, :method=>"block (3 levels) in start"},
          {:filename=>"/home/user/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb", :lineno=>294, :method=>"realtime"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>150, :method=>"block (4 levels) in start"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>186, :method=>"work_off"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>186, :method=>"times"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>187, :method=>"block in work_off"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>280, :method=>"reserve_and_run_one_job"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>40, :method=>"run_callbacks"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"execute"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"block in initialize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>280, :method=>"block in reserve_and_run_one_job"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>203, :method=>"run"},
          {:filename=>"/home/user/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/benchmark.rb", :lineno=>294, :method=>"realtime"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>204, :method=>"block in run"},
          {:filename=>"/home/user/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb", :lineno=>70, :method=>"timeout"},
          {:filename=>"/home/user/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb", :lineno=>70, :method=>"catch"},
          {:filename=>"/home/user/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/timeout.rb", :lineno=>82, :method=>"block in timeout"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb", :lineno=>204, :method=>"block (2 levels) in run"},
          {:filename=>"(eval)", :lineno=>2, :method=>"invoke_job_with_newrelic_transaction_trace"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/newrelic_rpm-3.13.0.299/lib/new_relic/agent/instrumentation/controller_instrumentation.rb", :lineno=>362, :method=>"perform_action_with_newrelic_trace"},
          {:filename=>"(eval)", :lineno=>3, :method=>"block in invoke_job_with_newrelic_transaction_trace"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb", :lineno=>91, :method=>"invoke_job"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>40, :method=>"run_callbacks"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"execute"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>66, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"block in add"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"block in initialize"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>61, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"block (2 levels) in add"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb", :lineno=>79, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/rollbar-2.2.1/lib/rollbar/delayed_job.rb", :lineno=>9, :method=>"block in wrap_worker"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/rollbar-2.2.1/lib/rollbar/delayed_job.rb", :lineno=>9, :method=>"call"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb", :lineno=>94, :method=>"block in invoke_job"},
          {:filename=>"/home/user/app/releases/20150907220425/lib/jobs/push_notification_job.rb", :lineno=>6, :method=>"perform"},
          {:filename=>"/home/user/app/releases/20150907220425/app/models/apns.rb", :lineno=>18, :method=>"notify"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb", :lineno=>91, :method=>"method_missing"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/associations/collection_proxy.rb", :lineno=>91, :method=>"each"},
          {:filename=>"/home/user/app/releases/20150907220425/app/models/apns.rb", :lineno=>19, :method=>"block in notify"},
          {:filename=>"/home/user/app/releases/20150907220425/app/models/apns.rb", :lineno=>26, :method=>"send"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/pusher.rb", :lineno=>8, :method=>"push"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/connection.rb", :lineno=>23, :method=>"write"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/connection.rb", :lineno=>55, :method=>"with_connection"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/connection.rb", :lineno=>29, :method=>"connect"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb", :lineno=>43, :method=>"connect"},
          {:filename=>"/home/user/app/shared/bundle/ruby/2.1.0/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb", :lineno=>43, :method=>"connect"}
        ],
        :exception=>{
          :class=>"OpenSSL::SSL::SSLError",
          :message=>"SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A"
        },
        :extra=>{}
      }
    },
    :uuid=>"a588ae56-62eb-465c-8110-a2c20d000784",
    :request=>#<Delayed::Backend::ActiveRecord::Job id: 6720989, priority: 0, attempts: 0, handler: "--- !ruby/object:PushNotificationJob\nargs:\n- 2\n- 'O...", last_error: nil, run_at: "2015-09-07 22:09:10", locked_at: "2015-09-07 22:09:12", failed_at: nil, locked_by: "delayed_job host:app-server pid:16785", created_at: "2015-09-07 22:09:10", updated_at: "2015-09-07 22:09:10", queue: nil>
  }
}
/home/user/app/shared/bundle/ruby/2.1.0/gems/rollbar-2.2.1/lib/rollbar/delayed_job.rb:9:in `call''
/home/user/app/shared/bundle/ruby/2.1.0/gems/rollbar-2.2.1/lib/rollbar/delayed_job.rb:9:in `block in wrap_worker''
```

**Comment by jondeandres** [comment]
@KieranP this is related to a bug between JSON gem and ActiveSupport. The bug exists since both implements a `#to_json` and ActiveSupport defines a `#to_json` for `Object` overriding default `to_s` that JSON gem has for `Object.

We are still finding a solution for this without monkey patch those gems.

**Comment by KieranP** [comment]
@jondeandres Wouldn't it be safer to call the rubygems directly then, instead of relying on .to_json?

e.g. ```JSON.generate(my_hash)```

**Comment by jondeandres** [comment]
@KieranP we are using `JSON.generate` in the gem. The problem is that both JSON and ActiveSupport defines `#to_json`, and at some cases, JSON relies on `#to_json`. That depending on the loading order, will be the method defined by ActiveSupport.

**Comment by epifanov** [comment]
Hi guys,

we faced this problem today too. It would be good to get some solution.

**Comment by jondeandres** [comment]
@epifanov your problem is using delayed_job?

**Comment by epifanov** [comment]
@jondeandres yes

**Comment by FranMoya** [comment]
Hi, I'm having the same problem that @jondeandres I'm using delayed_job in some tasks and I'm getting 'Failsafe from rollbar-gem: error in process_payload' error, please , is there any solution?

**Comment by jondeandres** [comment]
Hi @FranMoya ,

which gem version are you using?

**Comment by FranMoya** [comment]
hi @jondeandres ,currently I'm using  2.1.2 rollbar version

**Comment by jondeandres** [comment]
@FranMoya we released version 2.3.0 some days ago, fixing a problem reporting using delayed_job, https://github.com/rollbar/rollbar-gem/blob/v2.3.0/CHANGELOG.md#230.

Could you try it and check is solving your problem?

Thanks!

**Comment by FranMoya** [comment]
ok, I've updated to 2.3.0 version, good work :+1:  I'll deploy and check in my production enviroment. Thanks a lot @jondeandres

**Comment by jondeandres** [comment]
Awesome @FranMoya! Contact us if you need somewhere else!

**Comment by FranMoya** [comment]
hi @jondeandres I updated rollbar version but I keep getting same error "Failsafe from rollbar-gem: error in process_payload". Do I have to do something else, maybe change initializers config?
Thank you :+1:

**Comment by jondeandres** [comment]
Hi @FranMoya,

in https://github.com/rollbar/rollbar-gem/issues/94#issuecomment-142903734 you say this was working fine. So, this is another problem? Do you have logs?

It'd be nice see those logs you can find greping [Rollbar] on them. Maybe the problem is related to another issue?

Thanks.

**Comment by FranMoya** [comment]
hi @jondeandres I couldn't check it at all in production enviroment, but today I've noticed in rollbar message the following field -> "notifier.version	2.1.2"
It looks like gem wouldn't be updated in production enviroment, isn't it?

**Comment by jondeandres** [comment]
@FranMoya yes, if the version is 2.1.2 seems the correct and last version has not been installed. Could  you check that? Maybe your Gemfile line for rollbar is not the correct one.

**Comment by FranMoya** [comment]
@jondeandres I've checked my gemfile and my gemfile.lock and everything seems to be alright
Gemfile:    gem 'rollbar', '~> 2.3.0'
Gemfile.lock:  rollbar (2.3.0)
                              oj (~> 2.12.14)

**Comment by jondeandres** [comment]
@FranMoya we always send the current value for `Rollbar::VERSION`. This may be caused by an old process running maybe?

Or it may be an old item processed with some delay? That error seems to be definitely caused by 2.1.2 version of the gem. Can you check the notifier version in your current occurrences? So we can figure out if you are using the correct gem version or not.

**Comment by FranMoya** [comment]
yeah @jondeandres this early morning I noticed that in newest reports come with 2.3.0 version. It looks like old processes in backlog, thanks you're great :)
:+1:

**Comment by jondeandres** [comment]
awesome :smile:!

If you have any other problem contact us!

Cheers!

**Comment by masterkain** [comment]
I have this error on the most recent version:

`Failsafe from rollbar-gem. TypeError in /app/vendor/bundle/ruby/2.2.0/gems/rollbar-2.5.2/lib/rollbar.rb:375:in `[]': build_payload in exception_data`

```
{
  "body": {
    "message": {
      "body": "Failsafe from rollbar-gem. TypeError in /app/vendor/bundle/ruby/2.2.0/gems/rollbar-2.5.2/lib/rollbar.rb:375:in `[]': build_payload in exception_data"
    }
  }, 
  "failsafe": true, 
  "uuid": "c057f02389994771819015700b245d17", 
  "level": "error", 
  "timestamp": 1453721484, 
  "environment": "staging", 
  "framework": "unknown", 
  "internal": true, 
  "notifier": {
    "version": "2.5.2", 
    "name": "rollbar-gem"
  }, 
  "metadata": {}
}
```

**Comment by jmervine** [comment]
Hello,

I also saw this issue just now...

```
Failsafe from rollbar-gem. Net::ReadTimeout in /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': error in process_payload
```

Things to note:

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]

$ cat Gemfile.lock | grep rollbar
    rollbar (2.7.1)
  rollbar
```

Please let me know if you need additional information.

**Comment by Crisfole** [comment]
We're investigating these timeouts in a bit more depth and were hoping you'd be able to provide us with a few more details about your system and the errors:

 * Timestamps for any TimeoutErrors you've seen (including seconds)
 * The location of the server making the request that timed out.
 * Any IP addresses of servers making timed out requests to Rollbar.
 * The output of ping api.rollbar.com (obviously from the server that experienced the timeout).

If these are associated with Rollbar items, all the better, we'd love the links to those items.

If any of that data is sensitive, please send it to support@rollbar.com.  We want to make sure Rollbar is working really well for you.

**Comment by szymonbaranowski** [comment]
Hi. Same issue as one @jmervine reported.

`Failsafe from rollbar-gem. Net::ReadTimeout in /app/vendor/ruby-2.3.0/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': error in process_payload`

using `ruby 2.3.0` and and `rollbar 2.8.3`

**Comment by jondeandres** [comment]
hi @szymonbaranowski, those are caused by timeouts in the connection.

A couple of releases ago we did a change so we catch those errors and retry the reques up to 3 times, so we minimize these exceptions.

Can you try upgrading? Thanks
