### ISSUE TITLE
[BUG] Version 2.9.0 breaks Sidekiq support

### ISSUE THREAD

**Issue by phlipper** [rollbar/rollbar-gem#422]
The new middleware update introduced in #421 is broken. The `chain` variable is missing on [line 46](https://github.com/rollbar/rollbar-gem/pull/421/files#diff-23aec9cb4c3db31268a765b02619880cR46) of `lib/rollbar/sidekiq.rb`. This results in the following stack trace:

```
started with pid 25175
undefined local variable or method `chain' for main:Object
/.bundle/ruby/2.3.0/gems/rollbar-2.9.0/lib/rollbar/sidekiq.rb:46:in `block in <top (required)>'
/.bundle/ruby/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq.rb:69:in `configure_server'
/.bundle/ruby/2.3.0/gems/rollbar-2.9.0/lib/rollbar/sidekiq.rb:40:in `<top (required)>'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/.bundle/ruby/2.3.0/gems/rollbar-2.9.0/lib/rollbar.rb:880:in `require_hooks'
/.bundle/ruby/2.3.0/gems/rollbar-2.9.0/lib/rollbar.rb:863:in `prepare'
/.bundle/ruby/2.3.0/gems/rollbar-2.9.0/lib/rollbar.rb:833:in `configure'
/config/initializers/rollbar.rb:4:in `<top (required)>'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `call'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/.rubies/ruby-2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `public_send'
/.bundle/ruby/2.3.0/gems/railties-4.2.6/lib/rails/railtie.rb:194:in `method_missing'
/config/environment.rb:8:in `<top (required)>'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/.bundle/ruby/2.3.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/.bundle/ruby/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:233:in `boot_system'
/.bundle/ruby/2.3.0/gems/sidekiq-4.1.1/lib/sidekiq/cli.rb:49:in `run'
/.bundle/ruby/2.3.0/gems/sidekiq-4.1.1/bin/sidekiq:12:in `<top (required)>'
/.bundle/ruby/2.3.0/bin/sidekiq:23:in `load'
/.bundle/ruby/2.3.0/bin/sidekiq:23:in `<main>'
exited with code 1
sending SIGTERM to all processes
```

**Comment by jondeandres** [comment]
@phlipper thanks a lot for the report, we're sorry for this bug.

We've release 2.9.1.

**Comment by phlipper** [comment]
@jondeandres thank you very much!
