### ISSUE TITLE
rollbar/capistrano.rb recipe doesn't work with Ruby 1.9.2

### ISSUE THREAD

**Issue by troex** [rollbar/rollbar-gem#35]
According to the [ruby doc](http://www.ruby-doc.org/stdlib-1.9.2/libdoc/uri/rdoc/URI/Generic.html) — 1.9.2 doesn't have `hostname` method, but 1.9.3 [has](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/uri/rdoc/URI/Generic.html#method-i-hostname).

```
* 2013-04-17 10:00:25 executing `rollbar:deploy'
  * executing "cat /deploy/current/REVISION"
    servers: ["www"]
    [www] executing command
    command finished in 167ms
/home/alex/.rvm/gems/ruby-1.9.2-p320/gems/rollbar-0.9.6/lib/rollbar/capistrano.rb:35:in `block (3 levels) in load_into': undefined method `hostname' for #<URI::HTTPS:0x000000034f9d38> (NoMethodError)
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `instance_eval'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:138:in `invoke_task_directly'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:25:in `invoke_task_directly_with_callbacks'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/callback.rb:38:in `call'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `block in trigger'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `each'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:141:in `trigger'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/callbacks.rb:27:in `invoke_task_directly_with_callbacks'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:89:in `execute_task'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/configuration/execution.rb:101:in `find_and_execute_task'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:46:in `block in execute_requested_actions'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `each'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:45:in `execute_requested_actions'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/help.rb:19:in `execute_requested_actions_with_help'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:34:in `execute!'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/lib/capistrano/cli/execute.rb:14:in `execute'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/gems/capistrano-2.14.2/bin/cap:4:in `<top (required)>'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/bin/cap:19:in `load'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/bin/cap:19:in `<main>'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/alex/.rvm/gems/ruby-1.9.2-p320/bin/ruby_noexec_wrapper:14:in `<main>'
```
