### ISSUE TITLE
Failsafe error since upgrading from 2.14.1 to 2.15.1

### ISSUE THREAD

**Issue by KieranP** [rollbar/rollbar-gem#633]
I upgraded rollbar version the other day and have started getting failsafe errors every so often that I wasn't getting previously:

```
Failsafe from rollbar-gem. NoMethodError: "undefined method `strip' for nil:NilClass" in /app/shared/bundle/ruby/2.1.0/gems/rollbar-2.15.1/lib/rollbar/request_data_extractor.rb:116:in `rollbar_url': build_item in exception_data
```

The breakage appears to trace back to this commit: https://github.com/rollbar/rollbar-gem/commit/5664ea6ceb9b447bba22d2999652b48df95a2a46

It doesn't affect every error, there are still quite a few coming through normally, but these failsafe errors weren't happening prior to the upgrade.

**Comment by KieranP** [comment]
This issue is still present in 2.15.2. Can we please apply the PR from @rokob and get this issue fixed. Am getting frequent rollbar failsafe errors.

**Comment by rokob** [comment]
Released in v2.15.3
