### ISSUE TITLE
`present?` call fails in non active-support projects

### ISSUE THREAD

**Issue by kpricorn** [rollbar/rollbar-gem#84]
I integrated the rollbar gem in a non-rails/active-support project with this snippet [1](https://github.com/rollbar/sinatra-rollbar-example/blob/master/example.rb). After upgrading from 0.11.7 to 0.12.8, the `Rollbar.report_exception` call fails with the following exception:

```
NoMethodError: undefined method `present?' for nil:NilClass
  File "<snip>/vendor/bundle/ruby/2.0.0/gems/rollbar-0.12.8/lib/rollbar.rb" line 80 in report_exception
```

The `present?` check was introduced in [2](https://github.com/rollbar/rollbar-gem/commit/294ff03616f754b8aef85a9f66c7e8eaf1b8d67f)
