### ISSUE TITLE
rollbar-rails-runner works not well with rails 3.x and 4.0

### ISSUE THREAD

**Issue by ctokoro** [rollbar/rollbar-gem#273]
I've got exception in execute ```rollbar-rails-runner``` with code which contains define method.
this is sample code.
            
#### test.rb
```ruby
def say
  puts "HELLO"
end

say
```

#### rails runner
```
$ cd rails32_application

$ bundle exec rails r test.rb 
HELLO

$ bundle exec rollbar-rails-runner test.rb
test.rb:5:in `eval_runner': undefined local variable or method `say' for Rails:Module (NameError)
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:94:in `eval'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:94:in `eval_runner'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:41:in `module_eval'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:41:in `eval_runner'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:30:in `block in run'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:47:in `rollbar_managed'
	from /private/var/www/rollbar-gem/lib/rails/rollbar_runner.rb:30:in `run'
	from /private/var/www/rollbar-gem/bin/rollbar-rails-runner:5:in `<top (required)>'
	from /private/var/www/rails32_application/.bundle/bin/rollbar-rails-runner:16:in `load'
	from /private/var/www/rails32_application/.bundle/bin/rollbar-rails-runner:16:in `<main>'
```

i checked it works fine with rails 4.1 and later, and I found it is fixed by above commit of rails.

load the file rather than evaling · rails/rails@bc8eaf0
https://github.com/rails/rails/commit/bc8eaf0f5b90d0af5fa996649a5133953dd45086

but im using rails 3.2,  could you check it or give me any suggestion?

**Comment by jondeandres** [comment]
Hi @ctokoro,

could you change test.rb so it has some module namespace? Ex:

```ruby
# test.rb
module MyModule
  extend self

  def say
    puts "HELLO"
  end
end

MyModule.say
```

If you see at the runner code in Rails you can see that provide this functionality is too hacky, so probably it can break in some scenarios. Really rails runner is not prepared for this.

Try this and let us know if it works.

BTW, thanks for sharing the change in https://github.com/rails/rails/commit/bc8eaf0. We'll try to provide  compatibility with that version too.

**Comment by ctokoro** [comment]
Hello @jondeandres , thanks your reply. 

I've tried your suggestion of code, define some module namespace, and it works.
I can fix code of runner files as like it, but it will takes a time a bit, i prefer to fix the library if possible.

I forked and sent a pull-request about this issue. how do you think of it? https://github.com/rollbar/rollbar-gem/pull/280

**Comment by coryvirok** [comment]
@rokob can you take a look at this?
